export type ResourceFilter = {
  /** Exact data.gov.in filters[field] key */
  field: string;
  /** Tool argument name (defaults to field) */
  name?: string;
  describe: string;
};

export type ResourceToolDef = {
  name: string;
  title: string;
  description: string;
  resourceId: string;
  agency?: string;
  filters?: ResourceFilter[];
};

const f = (field: string, describe: string, name?: string): ResourceFilter => ({ field, describe, name });

/** Verified data.gov.in fixed-resource tools (Phases 2A–4F). */
export const RESOURCE_TOOL_DEFS: ResourceToolDef[] = [
  // --- 2A Land ---
  {
    name: "in_dilrmp_clr",
    title: "DILRMP Computerization of Land Records (RoR)",
    description: "State/UT-wise computerization of Record of Rights (RoR) under DILRMP from data.gov.in.",
    resourceId: "a8618f5c-5fd7-4cd4-ba02-e9371d17a6a2",
    agency: "Department of Land Resources",
    filters: [f("state_ut", "State/UT name, for example 'Karnataka'.", "state")],
  },
  {
    name: "in_dilrmp_registration",
    title: "DILRMP Sub-Registrar Office Computerization",
    description: "State/UT-wise computerization of Sub-Registrar Offices (SROs) under DILRMP.",
    resourceId: "25071cca-9cf6-4e80-adfd-ddcdcf618f56",
    agency: "Department of Land Resources",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
  {
    name: "in_dilrmp_maps",
    title: "DILRMP Cadastral Map Digitization",
    description: "State/UT-wise digitization of cadastral maps under DILRMP.",
    resourceId: "859a6bb9-acc0-4092-acd6-8f9596049d1c",
    agency: "Department of Land Resources",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
  {
    name: "in_dilrmp_funds",
    title: "DILRMP Funds Released by State",
    description: "Year-wise funds released to states/UTs under DILRMP.",
    resourceId: "63c490ad-e2c0-46ba-a5fe-bde80b991c8f",
    agency: "Department of Land Resources",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
  {
    name: "in_dilrmp_districts",
    title: "DILRMP Districts Covered",
    description: "Number of districts covered under DILRMP by state/UT.",
    resourceId: "e0044f1d-bba9-4da6-90ec-cfbee247c7b3",
    agency: "Department of Land Resources",
    filters: [f("states_ut", "State/UT name.", "state")],
  },
  {
    name: "in_dilrmp_northeast",
    title: "DILRMP Northeast Component Progress",
    description: "North-Eastern states DILRMP component-wise progress (CLR, maps, SROs, modern record rooms).",
    resourceId: "d45e628f-88e8-4440-9d51-9a598901a1df",
    agency: "Department of Land Resources",
    filters: [f("state", "North-Eastern state name.", "state")],
  },
  {
    name: "in_dilrmp_budget",
    title: "DILRMP / WDC Budget Utilisation",
    description: "Budget estimate, revised estimate, and utilisation for DILRMP/WDC.",
    resourceId: "089b3479-39bc-415c-802b-b9952828888d",
    agency: "Department of Land Resources",
    filters: [f("_year", "Financial year label as stored in the dataset.", "year")],
  },
  {
    name: "in_land_use_maharashtra",
    title: "Land Use Pattern — Maharashtra",
    description: "Land use categories and area (thousand ha) for Maharashtra.",
    resourceId: "0ce90a70-a714-4e77-817e-b6ac1cc9c286",
    filters: [f("land_use", "Land use category name.")],
  },
  {
    name: "in_land_use_chhattisgarh",
    title: "Land Use Pattern — Chhattisgarh",
    description: "Land use categories and area (thousand ha) for Chhattisgarh.",
    resourceId: "a9a473d6-691b-4a25-a995-23098f2a7abf",
    filters: [f("land_use", "Land use category name.")],
  },
  {
    name: "in_land_use_haryana",
    title: "Land Use Pattern — Haryana",
    description: "Land use categories and area (thousand ha) for Haryana.",
    resourceId: "8c06e8f1-3bb1-4299-b032-49ef2527d6a8",
    filters: [f("land_use", "Land use category name.")],
  },
  {
    name: "in_land_use_delhi",
    title: "Delhi Household / Land Indicators (linked resource)",
    description: "Rows from the data.gov.in resource linked as Delhi land use. Note: fields are household/LASI-style indicators, not classic land-use classes.",
    resourceId: "0c484052-8c1b-4ff9-a3fc-4fadc73b79ab",
    filters: [f("indicators", "Indicator name as stored in the Indicators field.")],
  },
  {
    name: "in_land_use_taluka",
    title: "Taluka-wise Land Use",
    description: "Taluka-wise fallen land, net area, and cultivated area.",
    resourceId: "a0b5a8e0-6146-443d-bb76-7a87017a1a6b",
    filters: [f("taluka", "Taluka name.")],
  },
  {
    name: "in_wasteland_district",
    title: "District Wasteland Area",
    description: "District-wise wasteland area for selected years.",
    resourceId: "3d6f37c7-fe12-4a00-a6f3-1e66dba0c83a",
    filters: [f("name_of_the_district", "District name.", "district")],
  },
  {
    name: "in_wasteland_treated",
    title: "Culturable Wasteland Treated (WDC-PMKSY)",
    description: "State/UT-wise WDC-PMKSY outcomes including culturable wasteland treated.",
    resourceId: "a568d98b-99f6-4726-af5a-6a603e650bcf",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
  {
    name: "in_land_acquisition_delays",
    title: "Projects Delayed due to Land Acquisition",
    description: "Projects with land required, acquired, and balance to be acquired.",
    resourceId: "ddc7d28f-fdbc-4d55-be72-97df5fee1ea9",
    filters: [f("name_of_the_project", "Project name.", "project")],
  },

  // --- 2B Tourism ---
  {
    name: "in_fta_by_age",
    title: "Foreign Tourist Arrivals by Age",
    description: "Year-wise foreign tourist arrivals with age-group distribution.",
    resourceId: "f6a89e6e-f900-4c59-975e-6967b85eef5c",
    agency: "Ministry of Tourism",
    filters: [f("year", "Year as stored in the dataset.")],
  },
  {
    name: "in_fta_by_country",
    title: "Foreign Tourist Arrivals by Nationality",
    description: "Foreign tourist arrivals by region and country of nationality.",
    resourceId: "6f81905b-5c66-458f-baa3-74f870de5cd0",
    agency: "Ministry of Tourism",
    filters: [
      f("region", "Region name."),
      f("country_of_nationality", "Country of nationality.", "country"),
    ],
  },
  {
    name: "in_approved_hotels",
    title: "Approved Hotels and Rooms (Latest Snapshot)",
    description: "Category-wise count of approved hotels and rooms.",
    resourceId: "f2cfc41a-b305-4d54-9682-4d944041b49c",
    agency: "Ministry of Tourism",
    filters: [f("category_of_hotels", "Hotel category.", "category")],
  },
  {
    name: "in_hotels_2019",
    title: "Approved Hotels and Rooms (2019)",
    description: "2019 category-wise approved hotels and rooms.",
    resourceId: "705ac8fe-591e-4787-8f55-0e7e1bad1c3b",
    agency: "Ministry of Tourism",
    filters: [f("category_of_hotels", "Hotel category.", "category")],
  },
  {
    name: "in_hotels_by_state",
    title: "Classified Hotels by State / Star",
    description: "State/UT-wise classified hotels by star category.",
    resourceId: "831cb80f-d729-4504-80cf-af7893dbc044",
    agency: "Ministry of Tourism",
    filters: [
      f("state_uts", "State/UT name.", "state"),
      f("category", "Category label as stored in the dataset."),
    ],
  },
  {
    name: "in_hotel_guests",
    title: "Hotel Guests by Category",
    description: "Guest composition across hotel star categories.",
    resourceId: "8a4245c3-1e26-4988-90a4-2e40d735f0be",
    agency: "Ministry of Tourism",
    filters: [f("composition", "Guest composition row label.")],
  },
  {
    name: "in_top_monuments",
    title: "Top ASI Ticketed Monuments",
    description: "Top 10 centrally protected ticketed monuments for domestic and foreign visitors.",
    resourceId: "02e72f1b-d82d-4512-a105-7b4373d6fa85",
    agency: "ASI / Ministry of Tourism",
  },
  {
    name: "in_monument_inflow",
    title: "Monument-wise Tourist Inflow",
    description: "Circle and monument-wise Indian/foreign tourist inflow.",
    resourceId: "93ea5b6a-7476-4240-8434-e334aacb6837",
    agency: "ASI / Ministry of Tourism",
    filters: [
      f("circle", "ASI circle name."),
      f("name_of_monument", "Monument name.", "monument"),
    ],
  },
  {
    name: "in_monument_revenue",
    title: "Monument Footfall and Ticket Revenue",
    description: "Monument footfall and ticket revenue.",
    resourceId: "7deaefd1-4a79-4b4d-9c9b-0b53f1a871ae",
    agency: "ASI / Ministry of Tourism",
    filters: [f("monuments", "Monument name.", "monument")],
  },
  {
    name: "in_monument_conservation",
    title: "Monument Conservation Funds",
    description: "Year-wise amount allocated and expenditure on monument conservation.",
    resourceId: "e0330456-aa9b-4d7a-8637-da706ad6f259",
    agency: "ASI / Ministry of Tourism",
    filters: [f("_year", "Year label.", "year")],
  },
  {
    name: "in_tourism_gdp",
    title: "Tourism Contribution to GDP",
    description: "Tourism share in GDP (direct and indirect).",
    resourceId: "9929bf20-394a-48c8-b944-1e2ba35d97e5",
    agency: "Ministry of Tourism",
    filters: [f("_year", "Year label.", "year")],
  },
  {
    name: "in_tourism_employment",
    title: "Tourism Contribution to Employment",
    description: "Tourism contribution to employment by year.",
    resourceId: "015013db-9937-4f58-8484-890fdf5d40c2",
    agency: "Ministry of Tourism",
  },
  {
    name: "in_tourism_infra",
    title: "Central Tourism Infrastructure Projects",
    description: "Centrally assisted tourism infrastructure projects by state/UT.",
    resourceId: "177572f5-102a-406e-80ac-40223899a73a",
    agency: "Ministry of Tourism",
    filters: [
      f("state_ut", "State/UT name.", "state"),
      f("name_of_project", "Project name.", "project"),
    ],
  },
  {
    name: "in_prashad_projects",
    title: "PRASHAD Projects by State",
    description: "PRASHAD scheme projects with sanction year, cost, and progress.",
    resourceId: "2636eeed-e5cf-4576-82ae-767cd7c18dd6",
    agency: "Ministry of Tourism",
    filters: [
      f("state_ut", "State/UT name.", "state"),
      f("project_name", "Project name.", "project"),
    ],
  },
  {
    name: "in_prashad_funds",
    title: "PRASHAD Budget / Expenditure",
    description: "Year-wise PRASHAD budget estimates and expenditure.",
    resourceId: "c1337530-2d70-42fd-9fc2-4a7fa2eec7d3",
    agency: "Ministry of Tourism",
    filters: [f("year_wise", "Year label.", "year")],
  },
  {
    name: "in_prashad_completed",
    title: "Completed PRASHAD Projects",
    description: "Completed PRASHAD projects by state/UT.",
    resourceId: "02753062-2183-4323-a58f-a5ea284efa4c",
    agency: "Ministry of Tourism",
    filters: [
      f("state_ut_wise", "State/UT name.", "state"),
      f("project_name", "Project name.", "project"),
    ],
  },
  {
    name: "in_tourism_festivals",
    title: "Fairs & Festivals Tourism Assistance",
    description: "Assistance sanctioned/released for fairs and festivals.",
    resourceId: "74ceeff8-dd4d-4388-a469-af12a813e183",
    agency: "Ministry of Tourism",
    filters: [
      f("_year", "Year label.", "year"),
      f("name_of_fairs___festivals", "Fair or festival name.", "festival"),
    ],
  },
  {
    name: "in_lighthouse_tourism",
    title: "Lighthouses Developed for Tourism",
    description: "State/UT-wise lighthouses developed for tourism.",
    resourceId: "6a5ab875-d240-4614-b359-485e09876391",
    filters: [
      f("state__ut", "State/UT name.", "state"),
      f("name_of_lighthouse", "Lighthouse name.", "lighthouse"),
    ],
  },
  {
    name: "in_tourist_places",
    title: "City Tourist Places (Smart Cities Sample)",
    description: "Sample city tourist places with category, access, and entry fee.",
    resourceId: "9c41624a-94f4-4cb3-a0fc-24aa963bc82c",
    filters: [
      f("city_name", "City name.", "city"),
      f("place", "Place name."),
      f("category_", "Category.", "category"),
    ],
  },

  // --- 2C Railway stats ---
  {
    name: "in_railway_route_km",
    title: "Railway Route Length (km)",
    description: "Year-wise railway route length by gauge (broad/metre/narrow).",
    resourceId: "cb5d0c04-000d-4bcf-beb1-0e9dcf52174c",
    agency: "Ministry of Railways",
    filters: [f("_year", "Year label.", "year")],
  },
  {
    name: "in_railway_earnings",
    title: "Railway Traffic and Passenger Earnings",
    description: "Railway traffic / passenger earnings particulars by year columns.",
    resourceId: "e10a5cca-06ea-4201-a8f9-0d76d8df21a7",
    agency: "Ministry of Railways",
    filters: [f("particulars", "Particulars row label.")],
  },
  {
    name: "in_railway_accidents",
    title: "State / Cause-wise Railway Accidents",
    description: "State/UT-wise railway accidents by cause (cases, injured, died).",
    resourceId: "b4a9433e-a762-4427-a84c-8e7bd31160ff",
    agency: "Ministry of Railways / NCRB",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
  {
    name: "in_railway_crossing_accidents",
    title: "Unmanned Crossing / Road-Rail Accidents",
    description: "Cause-wise unmanned crossing and related accident statistics.",
    resourceId: "62bb2ac5-ebf5-489d-9928-1d051bb8e1ce",
    filters: [f("cause", "Accident cause label.")],
  },
  {
    name: "in_railway_infra_gujarat",
    title: "Railway Infra Projects — Gujarat",
    description: "Railway infrastructure project categories for Gujarat.",
    resourceId: "f2d31cb3-4b5e-401a-9593-2004b524b542",
    filters: [f("category", "Project category.")],
  },
  {
    name: "in_railway_infra_wb",
    title: "Railway Infra Projects — West Bengal",
    description: "Railway infrastructure project categories for West Bengal.",
    resourceId: "750dfd29-b629-4220-bbf3-8e2ed4882058",
    filters: [f("category", "Project category.")],
  },
  {
    name: "in_grp_crimes",
    title: "Government Railway Police (IPC) Crimes",
    description: "State/UT-wise GRP IPC cognizable crimes.",
    resourceId: "015dfa82-0fa7-4d90-ac92-e7fe37a3ad2b",
    agency: "NCRB",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
  {
    name: "in_rpf_cases",
    title: "Railway Protection Force Cases",
    description: "State/UT-wise RPF cases under RP(UP) Act and Indian Railways Act.",
    resourceId: "a8555a65-8d6b-43c8-911e-cb399798e1d8",
    agency: "NCRB / Railways",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
  {
    name: "in_sll_railway_crimes",
    title: "GRP Special & Local Law Crimes",
    description: "State/UT-wise GRP SLL crimes.",
    resourceId: "e920a77f-125b-4691-a6da-a2f8ea74bc8f",
    agency: "NCRB",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
  {
    name: "in_railway_works_status",
    title: "Status of Suggested Railway Works",
    description: "Status of suggested railway works by type and subject.",
    resourceId: "99ee1583-40e3-4108-ad07-995d78ce3dc1",
    filters: [
      f("type", "Work type."),
      f("status", "Status label."),
    ],
  },
  {
    name: "in_land_acquisition_wb",
    title: "WB Projects Delayed by Land Acquisition",
    description: "West Bengal projects delayed due to land acquisition.",
    resourceId: "36cc5e04-d47a-4ee6-9fd6-a6b0bcd05c15",
    filters: [f("project", "Project name.")],
  },

  // --- 3A Fuel / LPG ---
  {
    name: "in_fuel_prices_delhi",
    title: "Delhi Petrol / Diesel Prices",
    description: "Effective-date petrol and diesel prices for Delhi.",
    resourceId: "02327d37-dbaa-4cf9-a908-a7eecc428d25",
    filters: [f("_effective_date", "Effective date as stored.", "effective_date")],
  },
  {
    name: "in_fuel_prices_delhi_avg",
    title: "Delhi Average Petrol / Diesel Prices",
    description: "Year-wise average petrol and diesel RSP for Delhi.",
    resourceId: "e336a512-2dfe-4e4b-8d00-bc1b11e41964",
    filters: [f("_year", "Year label.", "year")],
  },
  {
    name: "in_fuel_vat_by_state",
    title: "State Fuel Levies and RSP",
    description: "State/UT capital petrol/diesel levies and retail selling price.",
    resourceId: "8d939c2e-a2ff-4b7f-adc4-4372f7def526",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
  {
    name: "in_lpg_price_delhi",
    title: "Delhi LPG / Fuel RSP",
    description: "Year-wise Delhi petrol, diesel, and domestic LPG cylinder RSP.",
    resourceId: "4dc5b88c-f356-49d5-86e7-d8c4eb7c2a27",
    filters: [f("_year", "Year label.", "year")],
  },
  {
    name: "in_ethanol_blending",
    title: "Ethanol Supply / Blending Quantity",
    description: "Ethanol supply year quantities (crore litres).",
    resourceId: "1a0adf5b-7c45-4ed0-a9f3-80653c9b6d70",
    filters: [f("ethanol_supply_year__esy_", "Ethanol supply year label.", "year")],
  },

  // --- 3B Road accidents ---
  {
    name: "in_road_accidents_state_highways",
    title: "Road Accidents on State Highways",
    description: "State/UT-wise road accident counts and ranks on state highways.",
    resourceId: "3ad4e5c1-37a6-4b34-a851-2c88ba993347",
    agency: "MoRTH",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
  {
    name: "in_road_accidents_trend",
    title: "Road Accidents Trend by State",
    description: "State/UT-wise change in road accidents between years.",
    resourceId: "12d39b69-688d-48e4-8aae-6035bff3129f",
    agency: "MoRTH",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
  {
    name: "in_road_fatalities_nh",
    title: "Road Fatalities on National Highways",
    description: "State/UT-wise fatalities on national highways.",
    resourceId: "1b6954d8-2155-44cd-9027-a1ea711b93bb",
    agency: "MoRTH",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
  {
    name: "in_road_accidents_urban_rural",
    title: "Urban vs Rural Road Accidents",
    description: "State/UT-wise urban and rural road accident counts.",
    resourceId: "294bbc95-40d8-4877-9886-59e7e0ba0eba",
    agency: "MoRTH",
    filters: [f("state_ut", "State/UT name.", "state")],
  },

  // --- 3C Crime (NCRB, resolved via search) ---
  {
    name: "in_crime_ipc_by_state",
    title: "NCRB IPC Crimes by State (2023)",
    description: "Crime head-wise and State/UT-wise IPC crimes during 2023 (NCRB). Resource resolved via dataset search.",
    resourceId: "93550bf5-cc46-412c-beb3-d2e677bdb0a5",
    agency: "NCRB",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
  {
    name: "in_crime_sll_by_state",
    title: "NCRB SLL Crimes by State (2021)",
    description: "Crime head-wise & State/UT-wise SLL crimes during 2021 (newest stable state/UT SLL table found via search; 2023 state/UT matrix not listed).",
    resourceId: "8d963bec-c368-4677-9875-7832411a91bd",
    agency: "NCRB",
    filters: [f("state_ut_col___2_", "State/UT name.", "state")],
  },
  {
    name: "in_crime_against_women",
    title: "NCRB Crime against Women by State (2023)",
    description: "Crime head-wise and State/UT-wise IPC+SLL crimes against women during 2023 (NCRB).",
    resourceId: "fee6c4c1-0c08-4527-9887-16567ec56a7f",
    agency: "NCRB",
    filters: [f("state_ut", "State/UT name.", "state")],
  },

  // --- 3D Power ---
  {
    name: "in_renewable_energy_share",
    title: "Renewable Energy Share",
    description: "Year-wise percentage of energy generated through renewable sources.",
    resourceId: "a4e68e15-5c2e-4aa4-b884-e7f85fc8767c",
    filters: [f("_year", "Year label.", "year")],
  },
  {
    name: "in_renewable_capacity_state",
    title: "Renewable Capacity by State",
    description: "State/UT-wise renewable installed capacity by technology (MW).",
    resourceId: "7ae606e1-58b0-4b62-b268-03f4d8d3ce09",
    filters: [f("states___uts", "State/UT name.", "state")],
  },
  {
    name: "in_solar_parks",
    title: "Solar Parks",
    description: "Solar parks by state with sanctioned and installed capacity.",
    resourceId: "41653fa6-641f-476a-a6e3-974a201cf53c",
    filters: [
      f("state", "State name."),
      f("name_of_park", "Solar park name.", "park"),
    ],
  },
  {
    name: "in_power_supply_position",
    title: "Power Supply Position",
    description: "State/system region power requirement, availability, and surplus/deficit.",
    resourceId: "9056ba91-141c-455e-935b-0e424369c638",
    filters: [f("state_system_region", "State or system region.", "region")],
  },
  {
    name: "in_thermal_coal_statement",
    title: "Thermal Power Coal Statement",
    description: "Thermal power station coal receipts, consumption, and stocks.",
    resourceId: "558fcf41-7ec8-46b0-a2c6-2712bc3808ae",
    filters: [
      f("region", "Region name."),
      f("name_of_tps", "Thermal power station name.", "station"),
    ],
  },

  // --- 3E Water ---
  {
    name: "in_surface_water_quality",
    title: "Surface Water Quality",
    description: "Station-wise surface water quality parameters. Prefer state/district filters; dataset is large.",
    resourceId: "19697d76-442e-4d76-aeae-13f8a17c91e1",
    filters: [
      f("State", "State name.", "state"),
      f("District", "District name.", "district"),
      f("Station_Name", "Station name.", "station"),
      f("Year", "Year.", "year"),
    ],
  },
  {
    name: "in_jal_jeevan_habitation",
    title: "Jal Jeevan Mission Habitations",
    description: "Habitation-wise JJM coverage. Prefer state/district filters; dataset is large.",
    resourceId: "a7d77b40-59c7-4157-b29b-e114f7ec6c01",
    filters: [
      f("state_name", "State name.", "state"),
      f("district_name", "District name.", "district"),
      f("habitation_name", "Habitation name.", "habitation"),
      f("village_name", "Village name.", "village"),
    ],
  },
  {
    name: "in_reservoir_level",
    title: "Reservoir Levels",
    description: "Reservoir storage and level time series. Prefer reservoir/basin filters; dataset is large.",
    resourceId: "1fc2148c-fc41-46f5-a364-bdc03f77053f",
    filters: [
      f("Reservoir_name", "Reservoir name.", "reservoir"),
      f("Basin", "Basin name.", "basin"),
      f("Year", "Year.", "year"),
    ],
  },
  {
    name: "in_water_supply_surat",
    title: "Surat Water Supply (MLD)",
    description: "Date-wise water supplied in MLD for Surat.",
    resourceId: "d7d15ec2-7853-4932-b854-d65ed7abaf65",
    filters: [f("Date", "Date as stored.", "date")],
  },
  {
    name: "in_water_charges_surat",
    title: "Surat Water Charges",
    description: "Date-wise water charges for Surat.",
    resourceId: "dec710f2-7ee6-45cd-916f-da58f108fb2a",
    filters: [
      f("CityName", "City name.", "city"),
      f("Date", "Date as stored.", "date"),
    ],
  },

  // --- 3F Education AISHE ---
  {
    name: "in_aishe_foreign_students",
    title: "AISHE Foreign Students",
    description: "Year-wise number of foreign students in higher education.",
    resourceId: "fb4fe7e8-9d01-47bd-b8bc-f00f0c0239ff",
    agency: "AISHE",
    filters: [f("_year", "Year label.", "year")],
  },
  {
    name: "in_aishe_enrolment_category",
    title: "AISHE Enrolment by Category",
    description: "Higher education enrolment by category.",
    resourceId: "749ac757-71e5-4d45-bd8a-2f3478b420fd",
    agency: "AISHE",
    filters: [f("category", "Category label.")],
  },
  {
    name: "in_aishe_passout_by_state",
    title: "AISHE Pass-outs by State",
    description: "State/UT-wise pass-outs (all categories and Scheduled Tribes).",
    resourceId: "975b872a-68b9-4daf-aac1-c6b7964c1804",
    agency: "AISHE",
    filters: [f("state_ut", "State/UT name.", "state")],
  },

  // --- 3G Agri & petroleum products ---
  {
    name: "in_onion_production",
    title: "Onion Production",
    description: "Year-wise onion production (lakh tonnes).",
    resourceId: "8ba0d98c-0fd0-49e2-b5f0-556c72b65d43",
    filters: [f("_year", "Year label.", "year")],
  },
  {
    name: "in_crop_insurance",
    title: "Crop Insurance Coverage",
    description: "State-wise farmers insured under crop insurance schemes.",
    resourceId: "f6fb3ade-c752-4234-b8be-eee7b1578bea",
    filters: [f("state", "State name.")],
  },
  {
    name: "in_petroleum_products",
    title: "Petroleum Product Quantities",
    description: "Month/year-wise petroleum product quantities (000 MT).",
    resourceId: "8b75d7c2-814b-4eb2-9698-c96d69e5f128",
    agency: "PPAC",
    filters: [
      f("products", "Product name."),
      f("year", "Year."),
      f("month", "Month."),
    ],
  },

  // --- 4A–4F ---
  {
    name: "in_crude_oil_production",
    title: "Crude Oil Production",
    description: "Month/year-wise crude oil production by company (000 MT).",
    resourceId: "7932c3ed-c88d-4e0c-bc39-17e3e3170483",
    agency: "PPAC",
    filters: [
      f("company_name", "Company name.", "company"),
      f("year", "Year."),
      f("month", "Month."),
    ],
  },
  {
    name: "in_crude_oil_processed",
    title: "Crude Oil Processed",
    description: "Month/year-wise crude oil processed by oil companies (000 MT).",
    resourceId: "8d3b6596-b09e-4077-aebf-425193185a5b",
    agency: "PPAC",
    filters: [
      f("oil_companies_", "Oil company name.", "company"),
      f("year", "Year."),
      f("_month_", "Month.", "month"),
    ],
  },
  {
    name: "in_petroleum_trade",
    title: "Petroleum Import / Export Trade",
    description: "Crude and petroleum product import/export quantities and values.",
    resourceId: "518e560e-7fa7-4f5b-8aed-3b90323ed965",
    agency: "PPAC",
    filters: [
      f("PRODUCTS", "Product name.", "products"),
      f("TRADE", "Trade type, for example Import or Export.", "trade"),
      f("Year", "Year.", "year"),
      f("Month", "Month.", "month"),
    ],
  },
  {
    name: "in_steel_production",
    title: "Steel Production / Trade",
    description: "Steel production, consumption, import and export quantities.",
    resourceId: "829137af-5e90-4400-bffe-5d65b66e5956",
    filters: [
      f("PRODUCER_TYPE", "Producer type.", "producer_type"),
      f("DATA_TYPE", "Data type.", "data_type"),
      f("CAL_YEAR", "Calendar year.", "year"),
      f("MONTH", "Month name.", "month"),
    ],
  },
  {
    name: "in_cghs_wellness_beneficiaries",
    title: "CGHS Wellness Centre Beneficiaries",
    description: "Wellness centre-wise CGHS beneficiaries by city and card type.",
    resourceId: "f79de553-700c-4ef4-82f9-063b3ab5dfca",
    agency: "CGHS",
    filters: [
      f("CityName", "City name.", "city"),
      f("WellnessCentreName", "Wellness centre name.", "centre"),
      f("CardType", "Card type.", "card_type"),
    ],
  },
  {
    name: "in_cghs_hospitals",
    title: "CGHS Empanelled Diagnostic Centres (linked as hospitals)",
    description: "CGHS city-wise diagnostic centre directory from the roadmap hospitals resource ID (fields are diagnostic centres).",
    resourceId: "de59e770-2333-4eaf-9088-a3643de040c8",
    agency: "CGHS",
    filters: [
      f("CityName", "City name.", "city"),
      f("DiagnosticCentreName", "Centre name.", "name"),
    ],
  },
  {
    name: "in_cghs_diagnostics",
    title: "CGHS Diagnostic Centres",
    description: "CGHS diagnostic centre names and addresses by city.",
    resourceId: "34e827e1-03e0-4193-a0e7-1fcc62e306b5",
    agency: "CGHS",
    filters: [
      f("CityName", "City name.", "city"),
      f("DiagnosticCenterName", "Diagnostic centre name.", "name"),
    ],
  },
  {
    name: "in_cghs_dispensaries",
    title: "CGHS Dispensaries",
    description: "State/district/city-wise CGHS allopathy and AYUSH dispensary counts.",
    resourceId: "f55f64f0-3511-475a-9975-82485150933b",
    agency: "CGHS",
    filters: [
      f("state_ut", "State/UT name.", "state"),
      f("district", "District name."),
      f("city", "City name."),
    ],
  },
  {
    name: "in_hmis_facility_performance",
    title: "HMIS Facility Performance Indicators",
    description: "HMIS family-planning and related facility performance indicators.",
    resourceId: "d802b650-78a5-485c-89a9-5ad45a47938a",
    agency: "HMIS",
    filters: [f("indicators", "Indicator label.")],
  },
  {
    name: "in_cyclone_frequency",
    title: "Cyclone Frequency",
    description: "Year-wise cyclonic disturbances and cyclones (BoB/AS/land).",
    resourceId: "d3c39de0-35d6-4e80-83de-bd101fd2e13e",
    filters: [f("year", "Year.")],
  },
  {
    name: "in_cyclone_shelters",
    title: "Cyclone Shelters",
    description: "State-wise number of cyclone shelters constructed.",
    resourceId: "89e449ee-6820-4503-8f42-960711cdfcaa",
    filters: [f("state", "State name.")],
  },
  {
    name: "in_cyclone_damages",
    title: "Cyclone Damages",
    description: "State-wise cyclone damage statistics (lives, houses, cattle, crops).",
    resourceId: "a89e88bd-9b15-441b-aa6f-80e253d3997c",
    filters: [f("state", "State name.")],
  },
  {
    name: "in_forest_cover_india",
    title: "India Forest Cover",
    description: "India-wide forest cover assessments by density class.",
    resourceId: "ee07a310-7680-4ad3-9175-57e6033d2683",
    filters: [f("_year_", "Assessment year label.", "year")],
  },
  {
    name: "in_forest_cover_maharashtra",
    title: "Maharashtra Forest Cover",
    description: "District-wise forest cover for Maharashtra.",
    resourceId: "84d26d02-935b-479c-9427-c27ee1afd76f",
    filters: [f("district", "District name.")],
  },
  {
    name: "in_forest_cover_karnataka",
    title: "Karnataka Forest Cover",
    description: "District-wise forest cover for Karnataka.",
    resourceId: "dc39ada1-aa0f-4885-8490-21d242cfacc3",
    filters: [f("district", "District name.")],
  },
  {
    name: "in_wpi_inflation",
    title: "WPI Inflation",
    description: "Wholesale Price Index monthly values by year.",
    resourceId: "5bd65ce0-13b2-477e-a490-9dd0a1b5fc74",
    filters: [f("_year_wise_", "Year label.", "year")],
  },
  {
    name: "in_food_inflation_cfpi",
    title: "Food Inflation (CFPI)",
    description: "Month-wise Consumer Food Price Index / food inflation series.",
    resourceId: "e651fa87-53ff-4b80-9c43-67aabb0b209a",
    filters: [f("month", "Month name.")],
  },
  {
    name: "in_cpi_food_by_state",
    title: "CPI Food by State",
    description: "State/UT-wise CPI food index by year.",
    resourceId: "0e35257e-4f73-4708-b624-24f1d9fe942a",
    filters: [f("state_ut", "State/UT name.", "state")],
  },
];

export const RESOURCE_TOOL_NAMES = RESOURCE_TOOL_DEFS.map((def) => def.name);
